server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Désactive le buffering pour le flux SSE
    location /api/stream {
        proxy_pass         http://backend:8080;
        proxy_http_version 1.1;
        proxy_set_header   Connection "";
        proxy_buffering    off;
        proxy_cache        off;
        add_header         X-Accel-Buffering no;
    }

    location /api/ {
        proxy_pass       http://backend:8080;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
